baseURL: https://thilakm-git.github.io
title: Thilak Mahendran
theme: "PaperMod"

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowBreadCrumbs: false
  enableEmoji: true
  hideMeta: true
  searchHidden: true
  ShowPostNavLinks: true
  disableAnchoredHeadings: true
  hideSummary: true
  mainSections:
  cover:
    responsiveImages: true
  homeInfoParams:
    Title: hi, <br>i'm <mark>thilak.</mark> 
    Content: <mark>sr. tech consultant, public sector — [ibm ix {{< ext-svg >}}](https://ibmix.de/)</mark>
  socialIcons:
    - name: "mastodon"
      url: "https://ohai.social/@thilak"
    - name: "twitter"
      url: "https://twitter.com/thilakmahendran"
    - name: "linkedin"
      url: "https://linkedin.com/in/thilakmahendran"
    - name: "github"
      url: "https://github.com/thilakm-git"
  label:
    text: "home"
menu:
  main:
    - identifier: about
      name: about me
      url: "/about"
      weight: 10
    - identifier: work
      name: work
      url: "/work"
      weight: 20
    - identifier: media
      name: media
      url: "/media"
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true
