baseURL: https://thilakm-git.github.io
title: Thilak Mahendran
theme: "PaperMod"

params:
  defaultTheme: auto
  ShowBreadCrumbs: false
  enableEmoji: true
  hideMeta: true
  searchHidden: true
  ShowPostNavLinks: true
  disableAnchoredHeadings: true
  hideSummary: true
  cover:
    responsiveImages: true
  profileMode:
    enabled: true
    Title: Hi, I'm Thilak! 🖖🏾
    subtitle: Head of Open Data at the Federal Office of Administration, Germany.
    imageUrl: /profile.jpg
    imageWidth: 360
    imageHeight: 360
  socialIcons:
    - name: "mastodon"
      url: "https://ohai.social/@thilak"
    - name: "twitter"
      url: "https://twitter.com/thilakmahendran"
    - name: "linkedin"
      url: "https://linkedin.com/in/thilakmahendran"
    - name: "github"
      url: "https://github.com/thilakm-git"
  label:
    text: "thilak."
    #icon: /apple-touch-icon.png
    #iconHeight: 20
menu:
  main:
      - identifier: about
        name: about
        url: "/about"
        weight: 10
      - identifier: media
        name: media / activities
        url: "/media"
        weight: 20
